---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - lidopaglia.homebrew
    - lidopaglia.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/terminal.yml
      when: configure_terminal

    - include: tasks/macos.yml
      when: configure_macos